export const I18N = {
  LANG_CHANGE: 'I18N_LANG_CHANGE',
  LANG_EN: 'LANG_EN',
  LANG_CN: 'LANG_CN'
};

export const PAGES = {
  LIST: {
    SNAPSHOTS: {
      INIT: 'PAGES_LIST_SNAPSHOTS_INIT',
      RESET: 'PAGES_LIST_SNAPSHOTS_BIND',
      ADD: 'PAGES_LIST_SNAPSHOTS_ADD',
      DELETE: 'PAGES_LIST_SNAPSHOTS_DELETE',
      DELETE_OK: 'PAGES_LIST_SNAPSHOTS_DELETE_OK',
      MODIFY: 'LIST_SNAPSHOTS_MODIFY'
    },

    SNAPSHOT_EDIT: {
      CHANGE_DATE:'PAGES_LIST_SNAPSHOT_EDIT_CHANGE_DATE',
      NEW: 'PAGES_LIST_SNAPSHOT_EDIT_NEW',
      MODIFY: 'PAGES_LIST_SNAPSHOT_EDIT_MODIFY',
      SAVE: 'PAGES_LIST_SNAPSHOT_EDIT_SAVE',
      ADD_ASSET_ITEM: 'PAGES_LIST_SNAPSHOT_EDIT_ADD_ASSET_ITEM',
      MODIFY_ASSET_ITEM: 'PAGES_LIST_SNAPSHOT_EDIT_MODIFY_ASSET_ITEM',
      DELETE_ASSET_ITEM: 'PAGES_LIST_SNAPSHOT_EDIT_DELETE_ASSET_ITEM',
      IMPORT_ASSET_ITEMS_OF_LAST: 'PAGES_LIST_SNAPSHOT_EDIT_IMPORT_ASSET_ITEMS_OF_LAST',
      IMPORT_ASSET_ITEMS: 'PAGES_LIST_SNAPSHOT_EDIT_IMPORT_ASSET_ITEMS'
    },

    ASSET_ITEM_EDIT: {
      NEW: 'PAGES_LIST_ASSET_ITEM_EDIT_NEW',
      MODIFY: 'PAGES_LIST_ASSET_ITEM_EDIT_MODIFY',
      CHANGE_SAVE_BUTTION_STATUS: 'PAGES_LIST_ASSET_ITEM_EDIT_CHNAGE_SAVE_BUTTION_STATUS'
    }
  }
};
